/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;
import Functions.GlobalVariables;
import Functions.LinkedList;
import Functions.Node;
import Functions.User;
//Hacer import de Graph Modifier

/**
 *
 * @author victoriagarcia
 */
public class ModifyGraph extends javax.swing.JFrame {

    /**
     * Creates new form ModifyGraph
     */
    LinkedList userGraph = GlobalVariables.getUserGraph();
    LinkedList newUserOutRelations = new LinkedList();
    LinkedList newUserInRelations = new LinkedList();
    
    public ModifyGraph() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        UserNameComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        DeleteUserBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        NewUsernameTextField = new javax.swing.JTextField();
        UsernameComboBox = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        AddUserBtn = new javax.swing.JButton();
        AddRelationBtn = new javax.swing.JButton();
        RelationTypeToggleBtn = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UserNameComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UserNameComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserNameComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(UserNameComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 110, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setText("Usuarios Existentes");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        DeleteUserBtn.setText("Eliminar Usuario");
        DeleteUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(DeleteUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel2.setText("Nombre de usuario a agregar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        NewUsernameTextField.setText("Nombre");
        NewUsernameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewUsernameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(NewUsernameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 140, -1));

        UsernameComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        UsernameComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameComboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(UsernameComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, 141, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jLabel3.setText("Relacion con otro usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        AddUserBtn.setText("Agregar Usuario");
        AddUserBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddUserBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddUserBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, 21));

        AddRelationBtn.setText("Agregar Relacion");
        AddRelationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddRelationBtnActionPerformed(evt);
            }
        });
        jPanel1.add(AddRelationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        RelationTypeToggleBtn.setText("Relacion de entrada");
        RelationTypeToggleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelationTypeToggleBtnActionPerformed(evt);
            }
        });
        jPanel1.add(RelationTypeToggleBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, -1, -1));

        jButton1.setText("Atras");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/sodapdf-converted.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DeleteUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteUserBtnActionPerformed
        // TODO add your handling code here:
        String selection = (String)UsernameComboBox.getSelectedItem();
        Node user_to_delete = userGraph.getUser(selection);
        userGraph.delete(user_to_delete.getData());
        
        //Se puede poner borrado con exito en un popup message
    }//GEN-LAST:event_DeleteUserBtnActionPerformed

    private void NewUsernameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewUsernameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NewUsernameTextFieldActionPerformed

    private void AddUserBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddUserBtnActionPerformed
        // TODO add your handling code here:
        User newUser = new User(NewUsernameTextField.getText());
        Node pointer = newUserOutRelations.getHead();
        while(pointer != null){
            newUser.getRelations().append(pointer.getData());
            pointer = pointer.getNext();
        }
        pointer = newUserInRelations.getHead();
        while(pointer != null){
            User userIn = (User) pointer.getData();
            userIn.getRelations().append(newUser);
        }
        userGraph.append(newUser);
        
        //Mensaje de Usuario agregado con exito al grafo
    }//GEN-LAST:event_AddUserBtnActionPerformed

    private void RelationTypeToggleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelationTypeToggleBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelationTypeToggleBtnActionPerformed

    private void UserNameComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserNameComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserNameComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MainMenu mm = new MainMenu();
        this.dispose();
        this.setVisible(false);
        mm.setVisible(true);     
        mm.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void UsernameComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameComboBoxActionPerformed

    }//GEN-LAST:event_UsernameComboBoxActionPerformed

    private void AddRelationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddRelationBtnActionPerformed
        // TODO add your handling code here:
        if (!RelationTypeToggleBtn.isSelected()){
            String selection = (String) UserNameComboBox2.getSelectedItem();
            Node user_to_relate = userGraph.getUser(selection);
            newUserOutRelations.append(user_to_relate.getData());
        }else{
          String selection = (String) UserNameComboBox2.getSelectedItem();
            Node user_to_relate = userGraph.getUser(selection);
            newUserInRelations.append(user_to_relate.getData());  
        }
        
        
        //Mensaje de Relacion agregada con exito!
    }//GEN-LAST:event_AddRelationBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyGraph().setVisible(true);
            
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddRelationBtn;
    private javax.swing.JButton AddUserBtn;
    private javax.swing.JButton DeleteUserBtn;
    private javax.swing.JTextField NewUsernameTextField;
    private javax.swing.JToggleButton RelationTypeToggleBtn;
    private javax.swing.JComboBox<String> UserNameComboBox2;
    private javax.swing.JComboBox<String> UsernameComboBox;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
