/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package windows;

import Functions.GlobalVariables;
import Functions.GraphMaker;
import Functions.KosarajuFunctions;
import Functions.LinkedList;
import org.graphstream.graph.Graph;

/**
 *
 * @author victoriagarcia
 */
public class ShowGraph extends javax.swing.JFrame {

    /**
     * Creates new form ShowGraph
     */
    public ShowGraph() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        showGraphBtn = new javax.swing.JButton();
        showGraphBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        showGraphBtn.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        showGraphBtn.setText("Mostrar Grafo");
        showGraphBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphBtnActionPerformed(evt);
            }
        });
        jPanel1.add(showGraphBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        showGraphBtn1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        showGraphBtn1.setText("Mostrar Kosaraju");
        showGraphBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showGraphBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(showGraphBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 340, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/sodapdf-converted.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 390, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void showGraphBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphBtnActionPerformed

        Graph graph = GraphMaker.createVisualGraph();
        graph.display();
    }//GEN-LAST:event_showGraphBtnActionPerformed

    private void showGraphBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showGraphBtn1ActionPerformed
        KosarajuFunctions KosarajuFunctions = new KosarajuFunctions();
        KosarajuFunctions.findSCC();
        System.out.println(GlobalVariables.getSccGroupsList());
    }//GEN-LAST:event_showGraphBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowGraph.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowGraph().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton showGraphBtn;
    private javax.swing.JButton showGraphBtn1;
    // End of variables declaration//GEN-END:variables
}
